// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ServiceLocator.tt
using WPAppStudio.Ioc;
using WPAppStudio.Ioc.Interfaces;
using WPAppStudio.ViewModel;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Services
{
    /// <summary>
    /// Implementation of the ViewModel locator service based on IoC.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class ViewModelLocatorService
    {
        // IoC container
        private readonly IContainer _container;

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewModelLocatorService" /> class.
        /// </summary>
        public ViewModelLocatorService()
        {
            _container = new Container();
        }

        /// <summary>
        /// Gets the reference to a AboutIndiaViewModel.
        /// </summary>
		public IAboutIndiaViewModel AboutIndiaViewModel
        {
            get { return _container.Resolve<AboutIndiaViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a VideoAlbum_DetailVideosViewModel.
        /// </summary>
		public IVideoAlbum_DetailVideosViewModel VideoAlbum_DetailVideosViewModel
        {
            get { return _container.Resolve<VideoAlbum_DetailVideosViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a PhotoAlbum_DetailViewModel.
        /// </summary>
		public IPhotoAlbum_DetailViewModel PhotoAlbum_DetailViewModel
        {
            get { return _container.Resolve<PhotoAlbum_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a monuments_DetailViewModel.
        /// </summary>
		public Imonuments_DetailViewModel monuments_DetailViewModel
        {
            get { return _container.Resolve<monuments_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Disclaimer_InfoViewModel.
        /// </summary>
		public IDisclaimer_InfoViewModel Disclaimer_InfoViewModel
        {
            get { return _container.Resolve<Disclaimer_InfoViewModel>(); }
        }
    }
}
