// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// disclaimer_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class disclaimer : Idisclaimer 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"Every effort is made to provide accurate and complete information. However, with the lot of data&amp;nbsp;available on web&amp;nbsp;guaranteeing that there will be no errors is difficult. We have tried to use content using&amp;nbsp;creative commons licenses. However if you find any errors please notify us, and we will remove the content at earliest.&amp;nbsp;<br />";
        }
	}
}
