// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// monumentsCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class monumentsCollection : ImonumentsCollection 
    {
        private readonly ObservableCollection<monumentsCollectionSchema> _data = new ObservableCollection<monumentsCollectionSchema>
		{
          new monumentsCollectionSchema
            {
                Id= new Guid("bc56ca49-5609-4788-93fa-9037e3fb34c7"),
                Title=@"Agra Fort",
                Subtitle=@"Agra",
                Image=@"..\Images\Item-a7377023-708e-442e-8adc-b779742d2b4d.jpg",
                Description=@"Agra Fort, is a monument, It is a UNESCO World Heritage site located in Agra, Uttar Pradesh, India. It is about 2.5 km northwest of its more famous sister monument, the Taj Mahal. The fort can be more accurately described as a walled city. After Panipat,Mughals captured the fort and a vast treasure - which included a diamond that was later named as the Koh-i-Noor diamond - was seized. Babur stayed in the fort in the palace of Ibrahim. He built a baoli (step well) in it. Humayun was crowned here in 1530. Humayun was defeated in Bilgram in 1540. Sher Shah held the fort for five years. The Mughals defeated the Hindu King Hemu finally at the Second Battle of Panipat in 1556. It was only during the reign of Akbar's grandson, Shah Jahan, that the site took on its current state. The legend is that Shah Jahan built the beautiful Taj Mahal for his wife, Mumtaz Mahal. Unlike his grandfather, Shah Jahan tended to have buildings made from white marble, often inlaid with gold or semi-precious gems. He destroyed some of the earlier buildings inside the fort in order to make his own.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("0e2b42a3-49a0-4b2c-9895-91c694dfa0f6"),
                Title=@"Ajanta Caves",
                Subtitle=@"Aurangabad, Maharashtra",
                Image=@"..\Images\Item-715adeff-304c-4f83-8a60-60604024e409.jpg",
                Description=@"Ajanta caves including the unfinished ones are thirty in number; of which five - 9, 10, 19, 26 and 29 are 'Chaitya-Grihas' and the rest are 'Sangharamas' or 'Viharas' (monasteries). After centuries of oblivion, these caves of Ajanta were discovered in AD 1819. They fall into two distinct phases with a break of nearly four centuries between them. All the caves of the earlier phase date between 2nd century BC - AD. 


Ajanta caves of the second phase were excavated during the supremacy of the Vakatakas and Guptas. According to inscriptions, Varahadeva, the minister of the Vakataka king, Harishena (c. 475-500 AD), dedicated Cave 16 to the Buddhist Sangha while Cave 17 was the gift of the prince, a feudatory. An inscription records that - Buddha image in Cave 4 was the gift of some Abhayanandi who hailed from Mathura. 

A few paintings, which survive on the walls of Caves 9, and 10 go back to the 2nd century BC-AD. The second group of the Ajanta cave paintings started in about the 5th century AD and continued for the next two centuries as, noticeable in later caves. 

The themes are intensely religious in tone and centre round Buddha, Bodhisattvas, incidents from the life of Buddha and the 'Jatakas'. Ajanta cave paintings are executed on a ground of mud-plaster in the tempera technique.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("31b6c656-9e03-4fc4-9860-c4dab84d4b70"),
                Title=@"Charminar",
                Subtitle=@"Hyderabad",
                Image=@"..\Images\Item-8c5609c6-aa02-4c60-a36c-840127727054.jpg",
                Description=@"The charminar Hyderabad’s best known landmark was built 1591 by Sultan Mohammed Quli Qutub Shah to appease the force of evil savaging his new city with epidemic and plague. Standing in the heart of the old walled city and surround by lively bazaars, the charminar (‘four tower’) is a 56m high triumphal arch. The arch is notable for its elegant balconies, stucco decorations and the small mosque, Hyderabad’s oldest, on the 2nd floor. An image of the grace every packet of charminar cigarettes, one of India’s most popular brand.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("7c786138-f5c8-467b-9dc1-731b0bea04c3"),
                Title=@"Gateway of India",
                Subtitle=@"Mumbai",
                Image=@"..\Images\Item-3e8d647f-4dac-424a-b1e4-7381224c75bb.jpg",
                Description=@"The majestic Gateway of India is a glorious historical memorial built during British rule. This magnificent monument has been built in Indo-Sarcenic style to commemorate the visit of King George V and Queen Mary to Bombay. Gateway of India is one of the finest example of colonial architectural heritage in India. This grand structure stands at the Apollo Bunder, a popular meeting place in Mumbai. The gateway of India was designed by the British architect George Wittet and was opened for general public in the year 1924.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("c817d541-a8a2-431e-ab55-ed0a8c4dcb59"),
                Title=@"Hawa Mahal",
                Subtitle=@"Jaipur",
                Image=@"..\Images\Item-e71020dc-5532-4483-8491-9fb02edff436.jpg",
                Description=@"Hawa Mahal stands upright as the entrance to the City Palace, Jaipur. An important landmark in the city, Hawa Mahal is an epitome of the Rajputana architecture. The splendid five-storey “Palace of the Winds” is a blend of beauty and splendor much close to Rajasthan’s culture. Maharaja Sawai Pratap Singh built Hawa Mahal in 1779. The pyramid shape of this ancient monument is a tourist attraction having 953 small windows.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("4f2a4923-28eb-4239-b237-2bf8f95c5bf2"),
                Title=@"India Gate",
                Subtitle=@"New Delhi",
                Image=@"..\Images\Item-0e9bbe08-ce52-4ac8-879c-08f397d08947.jpg",
                Description=@"The India Gate is the national monument of India. Situated in the heart of New Delhi, the India Gate was designed by Sir Edwin Lutyens, inspired by the Arc de Triomphe in Paris. It was built in 1931. Originally known as the All India War Memorial, it is a prominent landmark in Delhi and commemorates the 90,000 soldiers of the Indian Army who lost their lives while fighting for the Indian Empire, or more correctly theBritish Raj, in World War I and the Third Anglo-Afghan War. It is composed of red and pale sandstone and granite
 
Originally, a statue of George V of the United Kingdom stood under the now vacant canopy in front of the India Gate, but it was removed to Coronation Park together with other statues. Following India's independence, the India Gate became the site of the Indian Army's Tomb of the Unknown Soldier, known as Amar Jawan Jyoti (""the flame of the immortal soldier""). 
",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("4d1bcf4e-698a-4a23-b867-c26d13c080c6"),
                Title=@"Khajuraho Temples",
                Subtitle=@"Madhya Pradesh",
                Image=@"..\Images\Item-90e72074-503c-4617-a03b-e616345adbdd.jpg",
                Description=@"Khajuraho is well known for erotic art sculptures and carved temples and Dance Festival.

Khajuraho, the ancient ""Kharjjuravahaka"", was the principal seat of authority of the Chandella rulers who adorned it with numerous tanks, scores of lofty temples of sculptural grace and architectural splendour. The local tradition lists eighty-five temples but now only twenty-five are standing examples in various stages of preservation. But for Chausath-Yogini, Brahma and Mahadeva, which are of granite, all the other temples are of fine-grained sandstone, buff, pink or pale yellow in colour. ",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("abe8edb7-234a-48da-a042-26179f7c7a0e"),
                Title=@"Qutab Minar",
                Subtitle=@"New Delhi",
                Image=@"..\Images\Item-02db33a5-e6e0-47c7-ba1d-9ade78f28a78.jpg",
                Description=@"Qutub-ud-din Aibak laid the foundation for Qutub Minar in 1199 AD and his successor and son-in-law Shamsu’d-Din- Iitutmish completed the structure by adding three more stories. Standing at 72.5 meters, it is the highest stone tower in India. Its base diameter is 14.3 meters and its top diameter is 2.7 meters. It has 379 steps leading to its top story. The lower three stories are made using red sand stone and the top two with marble and sand stone.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("8e0e8c6e-533e-40ea-b31b-5563e2b3941e"),
                Title=@"Red Fort (Lal Qila)",
                Subtitle=@"New Delhi",
                Image=@"..\Images\Item-558d7052-3707-412c-b09f-3b3393c0775a.png",
                Description=@"In 1638 when the emperor Shah Jahan moved the capital of India from Agra to Delhi, a new royal palace was constructed. Known as the Red Fort (Lal Qila), it was begun around 1640 and completed by 1648. 

The Red Fort served as the center of the Mughal Empire for more than 200 years. Lal Qila (Red Fort) is actually a series of individual pavilions, each with a specific purpose. The Khas Mahal served as the emperor's private quarters and was the most exquisitely decorated of all the pavilions. ",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("2c680ec0-2a96-4aba-a9f7-bfef35ad9358"),
                Title=@"Taj Mahal",
                Subtitle=@"Agra, Uttar Pradesh",
                Image=@"..\Images\Item-310327fd-0c29-45dc-9168-5a6ff1810d08.jpg",
                Description=@"Taj Mahal, the pinnacle of Mughal architecture, was built by the Mughal emperor Shah Jahan (1628-1658), grandson of Akbar the great, in the memory of his queen Arjumand Bano Begum, entitled ‘Mumtaz Mahal’. Mumtaz Mahal was a niece of empress Nur Jahan and granddaughter of Mirza Ghias Beg I’timad-ud-Daula, wazir of emperor Jehangir. She was born in 1593 and died in 1631, during the birth of her fourteenth child at Burhanpur. Her mortal remains were temporarily buried in the Zainabad garden. Six months later, her body was transferred to Agra to be finally enshrined in the crypt of the main tomb of the Taj Mahal. The Taj Mahal is the mausoleum of both Mumtaz Mahal and Shah Jahan.",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of monumentsCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of monumentsCollectionSchema items.</returns>
        public ObservableCollection<monumentsCollectionSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of monumentsCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of monumentsCollectionSchema items.</returns>
        public ObservableCollection<monumentsCollectionSchema> Search(FilterSpecification filter)
        {
            return Filter<monumentsCollectionSchema>.FilterCollection(filter, _data);
        }
	}
}
