// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// VideoAlbum_DetailVideos ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IVideoAlbum_DetailVideosViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentYouTubeVideo property.
        /// </summary>
		YouTubeVideo CurrentYouTubeVideo { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechVideoAlbum_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand ShareVideoAlbum_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand PinToStartVideoAlbum_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceVideoAlbum_DetailVideosStaticControlCommand { get; }

	}
}
