// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Disclaimer_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Disclaimer_InfoViewModel : BindableBase, IDisclaimer_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly Idisclaimer _disclaimer;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Disclaimer_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="disclaimer">The Disclaimer.</param>
        public Disclaimer_InfoViewModel(IDialogService dialogService, INavigationService navigationService, Idisclaimer disclaimer)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_disclaimer = disclaimer;
        }
		

		private string _currentDisclaimer_InfoHtmlControl;

        /// <summary>
        /// CurrentDisclaimer_InfoHtmlControl property.
        /// </summary>		
        public string CurrentDisclaimer_InfoHtmlControl
        {
            get
            {
                if(_currentDisclaimer_InfoHtmlControl == null)
					_currentDisclaimer_InfoHtmlControl = _disclaimer.Get();
				return _currentDisclaimer_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentDisclaimer_InfoHtmlControl, value);
            }
        }
    }
}
