// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of VideoAlbum_DetailVideos ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class VideoAlbum_DetailVideosViewModel : BindableBase, IVideoAlbum_DetailVideosViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoAlbum_DetailVideosViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public VideoAlbum_DetailVideosViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private YouTubeVideo _currentYouTubeVideo;

        /// <summary>
        /// CurrentYouTubeVideo property.
        /// </summary>		
        public YouTubeVideo CurrentYouTubeVideo
        {
            get
            {
				return _currentYouTubeVideo;
            }
            set
            {
                SetProperty(ref _currentYouTubeVideo, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechVideoAlbum_DetailVideosStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentYouTubeVideo.Title);
        }
		

        private ICommand _textToSpeechVideoAlbum_DetailVideosStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechVideoAlbum_DetailVideosStaticControlCommand
        {
            get { return _textToSpeechVideoAlbum_DetailVideosStaticControlCommand = _textToSpeechVideoAlbum_DetailVideosStaticControlCommand ?? new DelegateCommand(TextToSpeechVideoAlbum_DetailVideosStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
        public  void ShareVideoAlbum_DetailVideosStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentYouTubeVideo.Title, " ", CurrentYouTubeVideo.VideoUrl);
        }
		

        private ICommand _shareVideoAlbum_DetailVideosStaticControlCommand;

        /// <summary>
        /// Gets the ShareVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
        public ICommand ShareVideoAlbum_DetailVideosStaticControlCommand
        {
            get { return _shareVideoAlbum_DetailVideosStaticControlCommand = _shareVideoAlbum_DetailVideosStaticControlCommand ?? new DelegateCommand(ShareVideoAlbum_DetailVideosStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
        public  void PinToStartVideoAlbum_DetailVideosStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IVideoAlbum_DetailVideosViewModel), CreateTileInfoVideoAlbum_DetailVideosStaticControl());
        }
		

        private ICommand _pinToStartVideoAlbum_DetailVideosStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartVideoAlbum_DetailVideosStaticControlCommand
        {
            get { return _pinToStartVideoAlbum_DetailVideosStaticControlCommand = _pinToStartVideoAlbum_DetailVideosStaticControlCommand ?? new DelegateCommand(PinToStartVideoAlbum_DetailVideosStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
        public  void GoToSourceVideoAlbum_DetailVideosStaticControlCommandDelegate() 
        {
	
				_navigationService.NavigateTo(new Uri(CurrentYouTubeVideo.ExternalUrl));
        }
		

        private ICommand _goToSourceVideoAlbum_DetailVideosStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceVideoAlbum_DetailVideosStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceVideoAlbum_DetailVideosStaticControlCommand
        {
            get { return _goToSourceVideoAlbum_DetailVideosStaticControlCommand = _goToSourceVideoAlbum_DetailVideosStaticControlCommand ?? new DelegateCommand(GoToSourceVideoAlbum_DetailVideosStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is YouTubeVideo)) { return; }
                
                CurrentYouTubeVideo = value as YouTubeVideo;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the VideoAlbum_DetailVideosStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoVideoAlbum_DetailVideosStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentYouTubeVideo.VideoId,
                Title = CurrentYouTubeVideo.Title,
                BackTitle = CurrentYouTubeVideo.Title,
                BackContent = string.Empty,
                Count = 0,
                BackgroundImagePath = CurrentYouTubeVideo.VideoImageUrl,
                BackBackgroundImagePath = CurrentYouTubeVideo.VideoImageUrl,
                LogoPath = "Logo-eb4b8914-786c-479a-9e60-254e2bb0549e.png"
            };
            return tileInfo;
        }
    }
}
